### ISSUE TITLE
Error when .credentials file is missing

### ISSUE THREAD

**Issue by bromanko** [jaxxstorm/aws-sso-creds#41] opened 2023-06-26 12:58 UTC
I tried to run `aws-sso-creds set foo-temp -p foo` on a new machine with fresh awscli install. I got the following error:

```sh
/Users/bromanko/.aws/credentials
/Users/bromanko/.aws/config
Error: error parsing config file: open /Users/bromanko/.aws/credentials: no such file or directory
```

Fixed with `touch ~/.aws/credentials`.

Seems it would be better to detect when this file is missing and either create it or exit with an error message such as "Error storing credentials in /Users/bromanko/.aws/credentials. The file does not exist."

**Comment by jaxxstorm** [comment] 2023-06-26 19:46
@bromanko is there something about the error message that would be improved by the tool throwing a different message?

it seems to me based on the error, you knew the solution. I think this is as designed.

**Comment by bromanko** [comment] 2023-06-27 03:20
I only sorted it out because I looked at the source code. Nothing about what I was doing made it clear that file should exist. I suggest this would be clearer. “Error storing credentials in /Users/bromanko/.aws/credentials. The file does not exist. Please create it. "

**Comment by jaxxstorm** [comment] 2024-02-05 15:46
Closing as by design, this tool's job is to retrieve AWS temporary credentials, not guide you through AWS credentials set up

**Closed by jaxxstorm** 2024-02-05 15:46 UTC
